/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs414.a5.nwalling.employeeclient.views;

import cs414.a5.nwalling.employeeclient.controllers.ChefController;
import cs414.a5.nwalling.employeeclient.controllers.ViewController;
import cs414.a5.nwalling.common.data.IDataSource;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import cs414.a5.nwalling.common.models.IModel;

/**
 *
 * @author Jacob
 */
public class ChefView extends javax.swing.JPanel {

    private ViewController vc;
    private ChefController controller;
    private IDataSource source;
    private ArrayList<IModel> iOrders;
    private DefaultListModel<String> orders = new DefaultListModel<>();
    private DefaultListModel<String> completedOrders = new DefaultListModel<>();
    /**
     * Creates new form ChefView
     */
    public ChefView(ViewController vc, IDataSource source) {
        this.vc = vc;
        this.source = source;
        initComponents();
        initCustoms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        markDone = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        markDone.setText("Mark Done");
        markDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markDoneActionPerformed(evt);
            }
        });

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        ordersList.setModel(
            orders
        );
        jScrollPane1.setViewportView(ordersList);

        jList1.setModel(completedOrders);
        jScrollPane2.setViewportView(jList1);

        jLabel1.setText("Completed Orders");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(markDone))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(32, 32, 32)
                        .addComponent(done)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markDone)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(done, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        controller.submit();
        vc.showMainView();
    }//GEN-LAST:event_doneActionPerformed

    private void markDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markDoneActionPerformed
        // TODO add your handling code here:
        int[] completed = ordersList.getSelectedIndices();
        controller.removeOrders(completed);
    }//GEN-LAST:event_markDoneActionPerformed

    private void initCustoms(){
        controller = new ChefController(source);
        controller.init(orders,completedOrders);
       //ordersList.setModel(orders);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton markDone;
    private javax.swing.JList ordersList;
    // End of variables declaration//GEN-END:variables
}
