/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ChefController;
import controllers.ViewController;
import data.IDataSource;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import models.IModel;

/**
 *
 * @author Jacob
 */
public class ChefView extends javax.swing.JPanel {

    private ViewController vc;
    private ChefController controller;
    private IDataSource source;
    private ArrayList<IModel> iOrders;
    private DefaultListModel<String> orders = new DefaultListModel<>();
    /**
     * Creates new form ChefView
     */
    public ChefView(ViewController vc, IDataSource source) {
        this.vc = vc;
        this.source = source;
        initComponents();
        initCustoms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        markDone = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersList = new javax.swing.JList();

        markDone.setText("Mark Done");
        markDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markDoneActionPerformed(evt);
            }
        });

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        ordersList.setModel(
            orders
        );
        jScrollPane1.setViewportView(ordersList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(done)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markDone)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markDone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(done)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        controller.submit();
        vc.showMainView();
    }//GEN-LAST:event_doneActionPerformed

    private void markDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markDoneActionPerformed
        // TODO add your handling code here:
        int[] completed = ordersList.getSelectedIndices();
        controller.removeOrders(completed);
    }//GEN-LAST:event_markDoneActionPerformed

    private void initCustoms(){
        controller = new ChefController(source);
        controller.init(orders);
       //ordersList.setModel(orders);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markDone;
    private javax.swing.JList ordersList;
    // End of variables declaration//GEN-END:variables
}
