/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.OrderController;
import controllers.ViewController;
import data.IDataSource;
import javax.swing.JFrame;

/**
 *
 * @author Jacob
 */
public class OrderView extends javax.swing.JPanel {

    ViewController vc;
    
    private JFrame parent;
    /**
     * Creates new form OrderView
     */
    public OrderView(ViewController vc) {
        this.vc = vc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controller = new controllers.OrderController();
        totalLabel = new javax.swing.JLabel();
        TotalValue = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        receiptLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        addSelectedItem = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        menu = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        order = new javax.swing.JTextArea();
        itemSelectButton = new javax.swing.JButton();
        removeSelected = new javax.swing.JComboBox();
        removeSelectedButton = new javax.swing.JButton();

        totalLabel.setText("Total:");

        TotalValue.setText("$0.00");

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        receiptLabel.setText("Current Order:");

        menuLabel.setText("Menu:");

        menu.setEditable(false);
        menu.setColumns(20);
        menu.setLineWrap(true);
        menu.setRows(5);
        jScrollPane3.setViewportView(menu);

        order.setEditable(false);
        order.setColumns(20);
        order.setLineWrap(true);
        order.setRows(5);
        jScrollPane4.setViewportView(order);

        itemSelectButton.setText("Add Selected Item");

        removeSelectedButton.setText("Remove Selected Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(done))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(receiptLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(totalLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TotalValue))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(removeSelectedButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menuLabel)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(itemSelectButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(receiptLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemSelectButton)
                    .addComponent(addSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeSelectedButton)
                    .addComponent(removeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(TotalValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(done)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        vc.showMainView();
    }//GEN-LAST:event_doneActionPerformed

    public void initCustom(JFrame parent, IDataSource client)
    {
        controller = new OrderController();
        controller.init(client);
        this.parent = parent;
    }
    
    public void setMenu(String s){
        menu.setText(s);
    }
    
    public void setOrder(String s){
        order.setText(s);
    }
    
    public void addItemsToMenuSelect(String s){
        addSelectedItem.addItem(s);
    }
    
    public void addItemsToOrderSelect(String s){
        removeSelected.addItem(s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalValue;
    private javax.swing.JComboBox addSelectedItem;
    private controllers.OrderController controller;
    private javax.swing.JButton done;
    private javax.swing.JButton itemSelectButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea menu;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JTextArea order;
    private javax.swing.JLabel receiptLabel;
    private javax.swing.JComboBox removeSelected;
    private javax.swing.JButton removeSelectedButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
